stages:
  - build

flatpak:
    image: ananace/flatpak-builder:fdo-18.08
    stage: build
    script:
        - apt update
        - apt install -y git
        - git clone https://github.com/subins2000/varnam-flatpak.git flatpak
        - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        - flatpak-builder --repo=flatpak/repo --install-deps-from=flathub flatpak/build --keep-build-dirs flatpak/com.varnamproject.Varnam.json
        - flatpak build-bundle flatpak/repo varnam.flatpak com.varnamproject.Varnam.json
    artifacts:
        paths:
            - varnam.flatpak
    cache:
        paths:
            - .flatpak-builder/cache