stages:
  - build

package:
    image: registry.gitlab.com/subins2000/docker-images/flatpak-freedesktop:latest
    stage: build
    script:
        - git clone https://github.com/subins2000/varnam-flatpak.git flatpak
        - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        - flatpak-builder --repo=flatpak/repo flatpak/build --keep-build-dirs flatpak/com.varnamproject.Varnam.json
        - flatpak build-bundle flatpak/repo varnam.flatpak com.varnamproject.Varnam
    artifacts:
        paths:
            - varnam.flatpak
    cache:
        paths:
            - .flatpak-builder/cache